### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by Jeiel0rbit** [MidD3Vil/MidPainel#1]
```js
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/MidPainel/main.py", line 126, in <module>
    cpf.consultar()                                                                       File "/data/data/com.termux/files/home/MidPainel/database/cpf.py", line 40, in consultar
    rjson = request.json()
            ^^^^^^^^^^^^^^                                                                File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                         File "/data/data/com.termux/files/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0
```

Executei para fazer uma consulta de CPF e resultou nisso.

**Comment by victorbraga8** [comment]
Mesmo caso, porém ao consultar um nome.

**Comment by shunu482-arch** [comment]
O meu tbm tá assim  2026
